import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react"; // Import Suspense
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Interview Master",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.variable}>
        <ThemeProvider attribute="class" defaultTheme='light'>
          <Header />
          <Suspense fallback={<div>Loading...</div>}>
            {children}
          </Suspense>
          {/* //<Footer /> */}
        </ThemeProvider>
        </body>
    </html>
  );
}
